### ISSUE TITLE
Can't seem to gh > login, even though i have installed the workflow

### ISSUE THREAD

**Issue by g-tejas** [gharlan/alfred-github-workflow#132]
![Screenshot 2022-04-03 at 3 24 20 PM](https://user-images.githubusercontent.com/76802638/161416496-58b9cb46-9b56-46b2-80bc-7920980fd784.png)

**Comment by whomwah** [comment]
Console log output:

```
[14:07:09.977] ERROR: GitHub[Script Filter] JSON error: JSON text did not start with array or object and option to allow fragments not set. around line 1, column 0. in JSON:
Warning: Undefined array key "request_header" in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php on line 51

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php on line 123

Warning: Undefined array key "" in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php on line 52

Warning: Undefined array key 1 in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php on line 57

Warning: Attempt to read property "callback" on null in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php on line 73

Fatal error: Uncaught Error: Value of type null is not callable in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php:74
Stack trace:
#0 /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/workflow.php(297): Curl->execute()
#1 /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/workflow.php(358): Workflow::requestCache('https://api.git...', Object(Curl), Object(Closure), true, 1440)
#2 /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/search.php(41): Workflow::checkUpdate()
#3 /Users/duncan/Library/Caches/com.runningwithcrayons.Alfred/Workflow Scripts/1BCB75A0-AF04-436B-8A8C-FDD45FD627BD(5): Search::run('github', '', '0')
#4 {main}
  thrown in /Users/duncan/Documents/Apps/Alfred/Alfred.alfredpreferences/workflows/user.workflow.17EC552A-5327-4D14-B583-52F0799CC634/curl.php on line 74
```

**Comment by whomwah** [comment]
My issue was caused by a network monitor blocking PHP making outbound requests.

**Comment by ocardia** [comment]
To me it was just a matter of doing `brew upgrade php` (or install if you didn't yet).
