### ISSUE TITLE
Unable to run release v1.4.1

### ISSUE THREAD

**Issue by w11th** [gharlan/alfred-github-workflow#74]
Hi, I installed release v1.4.1, but I can`t type anything. The workflow will crash directly after typing 'gh<enter>'.

Env:
* macOS Sierra
* Alfred 3
* alfred-github-workflow release v1.4.1

The debug info in alfred:

<img width="1031" alt="2016-11-30 11 38 02" src="https://cloud.githubusercontent.com/assets/11044635/20738946/cfc29eb6-b6f1-11e6-983a-44c99435e2dc.png">

I can`t figure out the reason. Any suggestion for me? Thanks a lot.

**Comment by gharlan** [comment]
Did you change anything to the default php setup of Sierra?

**Comment by w11th** [comment]
No, I didn`t change anything about PHP.

I know few about PHP, so I google some commands to show my PHP configuration status.

<img width="334" alt="2016-12-06 10 51 55" src="https://cloud.githubusercontent.com/assets/11044635/20911316/2410027e-bba2-11e6-8511-bd44b18d9547.png">

Don`t know if it is clear. Thanks again for the help. 😃

**Comment by gharlan** [comment]
please try this version: [github.alfredworkflow.zip](https://github.com/gharlan/alfred-github-workflow/files/637602/github.alfredworkflow.zip)
It should give us a more useful error message in alfred debug window.

**Comment by w11th** [comment]
```
Starting debug for 'GitHub'

[2016-12-08 11:09:31][input.scriptfilter] <?xml version="1.0"?>
<items><item uid="19b19ffc30caef1c9376cd2982992a59" autocomplete=" " valid="no"><icon>icon.png</icon><title>gh&#x2026;</title><subtitle>Search or type a command</subtitle></item></items>
[2016-12-08 11:09:32][ERROR: input.scriptfilter] Code 255: Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: config' in /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php:404
Stack trace:
#0 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php(404): PDO->prepare('SELECT value FR...')
#1 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php(88): Workflow::getStatement('SELECT value FR...')
#2 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php(328): Workflow::getConfig('version')
#3 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/use in /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php on line 404
[2016-12-08 11:09:32][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: config' in /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php:404
Stack trace:
#0 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php(404): PDO->prepare('SELECT value FR...')
#1 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php(88): Workflow::getStatement('SELECT value FR...')
#2 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php(328): Workflow::getConfig('version')
#3 /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/use in /Users/w11th/Library/Mobile Documents/com~apple~CloudDocs/Alfred/Alfred.alfredpreferences/workflows/user.workflow.FC1731B9-E0F8-4CB8-812A-51C6044FD14D/workflow.php on line 404
```

**Comment by gharlan** [comment]
Please try to delete `/Users/<your user>/Library/Application Support/Alfred 3/Workflow Data/de.gh01.alfred.github/db.sqlite`

**Comment by w11th** [comment]
It worked! 🎉
The file `db.sqlite` was empty before deleting. 
Now it has the tables.

Thank you.

**Comment by controversial** [comment]
I had this error:
```
2017-02-12 14:13:18][ERROR: input.scriptfilter] Code 255: PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 1 no such table: config' in /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/workflow.php:428
Stack trace:
#0 /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/workflow.php(428): PDO->prepare('SELECT value FR...')
#1 /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/workflow.php(97): Workflow::getStatement('SELECT value FR...')
#2 /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/workflow.php(351): Workflow::getConfig('version')
#3 /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/search.php(41): Workflow::checkUpdate()
#4 /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/search.php(608): Search::run('gith in /Users/luke/Alfred/Alfred.alfredpreferences/workflows/user.workflow.6E6801BD-AD6C-43A5-839E-E9047D36F6A9/workflow.php on line 428
```

Deleting the database file was the fix.
