### ISSUE TITLE
Support for High Sierra

### ISSUE THREAD

**Issue by KyleKing** [gharlan/alfred-github-workflow#94]
I waited to install High Sierra Beta 7 and am now on Beta 8, but ever since upgrading, gh workflow has stopped working.

- Versions: MacOS 10.13 Beta / PHP 7.1.7 (cli) / Alfred-Github 1.6* / Alfred 3.4.1
- I deleted the workflow and installed the latest release, then re-authenticated
- I also tried deleting the cache directory/database* (https://github.com/gharlan/alfred-github-workflow/issues/82#issuecomment-285797924)
- The debug logs are below, how do I unlock the database? The error is similar to @dotemacs https://github.com/gharlan/alfred-github-workflow/issues/82#issuecomment-285774530

```
Starting debug for 'GitHub'

[2017-09-02 09:09:34][input.scriptfilter] Queuing argument ''
[2017-09-02 09:09:34][input.scriptfilter] Queuing argument ' '
[2017-09-02 09:09:34][input.scriptfilter] Script with argument '(null)' finished
[2017-09-02 09:09:34][input.scriptfilter] <?xml version="1.0"?>
<items><item uid="19b19ffc30caef1c9376cd2982992a59" autocomplete=" " valid="no"><icon>icon.png</icon><title>gh&#x2026;</title><subtitle>Search or type a command</subtitle></item></items>
[2017-09-02 09:09:43][input.scriptfilter] Queuing argument ' d'
[2017-09-02 09:09:43][input.scriptfilter] Queuing argument ' de'
[2017-09-02 09:09:43][input.scriptfilter] Queuing argument ' des'
[2017-09-02 09:09:43][input.scriptfilter] Queuing argument ' desk'
[2017-09-02 09:09:43][input.scriptfilter] Queuing argument ' deskt'
[2017-09-02 09:09:43][input.scriptfilter] Queuing argument ' deskto'
[2017-09-02 09:09:44][input.scriptfilter] Queuing argument ' desktop'
[2017-09-02 09:11:13][input.scriptfilter] Script with argument '(null)' finished
[2017-09-02 09:11:13][ERROR: input.scriptfilter] Code 255: using cached content for https://api.github.com/repos/gharlan/alfred-github-workflow/releases/latest
loading content for https://api.github.com/user?per_page=100
[2017-09-02 09:11:13][input.scriptfilter] Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php:247
Stack trace:
#0 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php(247): PDOStatement->execute(Array)
#1 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php(293): Workflow::{closure}(Object(CurlResponse), NULL)
#2 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/curl.php(74): Workflow::{closure}(Object(CurlResponse))
#3 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php(297): Curl->execute()
#4 /Use in /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php on line 247
[2017-09-02 09:11:13][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 5 database is locked in /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php:247
Stack trace:
#0 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php(247): PDOStatement->execute(Array)
#1 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php(293): Workflow::{closure}(Object(CurlResponse), NULL)
#2 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/curl.php(74): Workflow::{closure}(Object(CurlResponse))
#3 /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php(297): Curl->execute()
#4 /Use in /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.087B9005-DF96-4BD7-A1DB-7FF72C4FB6B9/workflow.php on line 247
[2017-09-02 09:11:29][input.scriptfilter] Queuing argument ' desktop'
```

The reminders workflow was also broken in High Sierra for an unknown reason as well (https://github.com/surrealroad/alfred-reminders/issues/59)

What should I try? I tested `php search.php github " dev.socrata"`, but I get the error `Could not open input file: search.php`

*Edits

**Comment by gharlan** [comment]
The main error is this: 

> General error: 5 database is locked

Quick fix: delete the database (https://github.com/gharlan/alfred-github-workflow/issues/82#issuecomment-285797924)

So it should be unrelated to High Sierra.

**Comment by KyleKing** [comment]
Yeah, I tried to delete the database again, but I have the same error

You're probably right that it isn't High Sierra, but since that was when the workflow stopped working I was curious if other people had the same issue

**Comment by KyleKing** [comment]
I tried removing then reinstalling the workflow again, but I get a new error:

From the Alfred Debug Console:

```
Starting debug for 'GitHub'

[2017-09-02 10:54:27][STDERR: input.scriptfilter] loading content for https://api.github.com/repos/gharlan/alfred-github-workflow/releases/latest
[2017-09-02 10:54:27][ERROR: input.scriptfilter] JSON error: JSON text did not start with array or object and option to allow fragments not set. in JSON:
Warning: curl_multi_remove_handle(): supplied resource is not a valid cURL handle resource in /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.8518B65F-07A8-47BD-BFAB-3B0467153020/curl.php on line 76

Warning: curl_multi_exec(): supplied resource is not a valid cURL handle resource in /Users/kyleking/MyDocuments/Dropbox (Personal)/Apps/Alfred.alfredpreferences/workflows/user.workflow.8518B65F-07A8-47BD-BFAB-3B0467153020/curl.php on line 44
<?xml version="1.0"?>
<items><item uid="d9a3a16d6f0f3fb027ce06d9a9ba44c8" arg="&gt; login" autocomplete=" &gt; login"><icon>icon.png</icon><title>&gt; login</title><subtitle>Generate OAuth access token</subtitle></item><item uid="f673b212b33873de91a53e3bdf5071f2" arg="&gt; login " autocomplete=" &gt; login " valid="no"><icon>icon.png</icon><title>&gt; login &lt;access_token&gt;</title><subtitle>Save access token</subtitle></item></items>
```

This appears in my browser when I try to login:

```
Warning: Unknown: failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Unknown: Failed opening required 'server.php' (include_path='.:') in Unknown on line 0
```

**Comment by vcarus** [comment]
Same issue here from beta 1 to now.
php cost very much CPU, but comes out of nothing.

**Comment by vcarus** [comment]
Got some idea about this issue.


When we run this workflow, Alfred calls system version of php. On macOS 10.13, it's php7.
Code of this workflow don't work properly on php7.

So, just change 'php' to _your own path_.
No more error.

**Comment by gharlan** [comment]
I'm on macOS 10.13 now and can confirm the issue.

Can you confirm that this is solved by this commit?
https://github.com/gharlan/alfred-github-workflow/commit/4802b437cb92ee594902e5041342689ac39cfb06

**Comment by KyleKing** [comment]
Thanks! It works now. I had to delete my cache directory/database (https://github.com/gharlan/alfred-github-workflow/issues/82#issuecomment-285797924) then login

**Comment by QuietWind** [comment]
I find this method with a lot of time， @gharlan  

resolve command: 

`rm -rf ~/Library/Application\ Support/Alfred\ 3/Workflow\ Data/de.gh01.alfred.github`
